CREATE TABLE posted_comments (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    text TEXT NOT NULL,
    date_created TIMESTAMP DEFAULT now() NOT NULL,
    postcard_id INTEGER
        REFERENCES posted_postcards(id) ON DELETE CASCADE NOT NULL,
    user_id INTEGER
        REFERENCES posted_users(id) ON DELETE CASCADE NOT NULL
);
